name: Build and Push Glacier Watch Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:


env: 
  IMAGE: ghcr.io/${{ github.repository_owner }}/glacier-watch


jobs:
  build:
    name: Build and Push Glacier Watch Docker Image
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read project version
        id: read_version
        uses: SebRollen/toml-action@v1.2.0
        with:
          file: "pyproject.toml"
          field: "project.version"
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if image with version exists
        id: check_image
        run: |
          response=$(gh api /users/${{ github.repository_owner }}/packages/container/${{ github.event.repository.name }}/versions)

          if echo "$response" | jq -e '.[] | select(.name == "${{ steps.read_version.outputs.value }}")' > /dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Image with this version already exists. Skipping build."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ steps.read_version.outputs.value }}
            ${{ env.IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max